{% set name = "keras-tuner" %}
{% set version = "1.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6befd25ee81476e6207d8ca7ed7dc674b8194437cfa0b127294cd00da905ff22

build:
  skip: True  # [py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - keras
    - packaging
    - requests
    - kt-legacy
    # extras for test imports
    - tensorflow >=2.0  # [not s390x]
    - tensorflow-cpu >=2.0  # [linux and not s390x]
    - pytorch  # [osx]

test:
  imports:
    - keras_tuner
    - keras_tuner.applications  # [not win and not s390x]
    - keras_tuner.engine  # [not win and not s390x]
    - keras_tuner.oracles  # [not win and not s390x]
    - keras_tuner.tuners  # [not win and not s390x]
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/keras-team/keras-tuner
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Hypertuner for Keras
  description: KerasTuner is an easy-to-use, scalable hyperparameter optimization framework that solves the pain points of hyperparameter search.
  doc_url: https://keras-team.github.io/keras-tuner/
  dev_url: https://github.com/keras-team/keras-tuner

extra:
  recipe-maintainers:
    - anselmoo
    - oblute
    - rluria14
    - Tata17
    - mxr-conda
