{% set name = "keras-tuner" %}
{% set version = "1.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6befd25ee81476e6207d8ca7ed7dc674b8194437cfa0b127294cd00da905ff22

build:
  # No tensorflow for python 3.13
  skip: True  # [py<37 or py>=313]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
    - pytorch  # [osx]
  run:
    - python
    - keras
    - packaging
    - requests
    - kt-legacy
    - tensorflow >=2.0
    - scikit-learn
    - scipy
    # Required on OSX as Keras 3.x has a hard dependency on PyTorch for certain operations.
    # This is due to Keras 3.x's multi-backend architecture where some operations on macOS
    # are optimized to use PyTorch's implementation. See:
    # https://github.com/keras-team/keras/blob/main/requirements.txt
    - pytorch  # [osx]
  run_constrained:
    - tensorflow-base >=2.0

test:
  imports:
    - keras_tuner
    - keras_tuner.applications
    - keras_tuner.src.backend
    - keras_tuner.src.distribute
    - keras_tuner.engine
    - keras_tuner.oracles
    - keras_tuner.src.protos
    - keras_tuner.tuners
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/keras-team/keras-tuner
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Hypertuner for Keras
  description: KerasTuner is an easy-to-use, scalable hyperparameter optimization framework that solves the pain points of hyperparameter search.
  doc_url: https://keras-team.github.io/keras-tuner/
  dev_url: https://github.com/keras-team/keras-tuner

extra:
  recipe-maintainers:
    - anselmoo
    - oblute
    - rluria14
    - Tata17
    - mxr-conda
